name: flutter_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  lottie: ^2.3.0
  preload_page_view: ^0.1.6
  image: ^3.3.0
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  image_picker: ^0.8.7+3
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  cloud_firestore: ^4.5.2
  provider: ^6.0.5
dependency_overrides:
  camera: ^0.10.4

flutter_icons:
  android: true
  image_path: "image/Trinity.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - C:/Users/moski/Downloads/app/flutter_app/image/Trinity.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/cloud_sun.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/cloud.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/wave.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Logo.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/sun.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Soda_Can.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Glass_Drink.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Untitled-1-final.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/ppp.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Group 36697.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Group 36718.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Group 36716.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Group 36719.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Group 36717.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Group 36722.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/1stbanner.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/splash_screen.json
    - C:/Users/moski/Downloads/app/flutter_app/pic/Trinity_text.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/bkname.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/homebk.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/small trinity.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Tri_text.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/navigator.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/demo_pic.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/home_icon.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/pictute_icon.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/global_icon.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/tri_card.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/camera_icon.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/image 297.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/funfueng.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/human.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/apex.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/cmkl.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/bk.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/triversion.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Gallery_pic.png
    - C:/Users/moski/Downloads/app/flutter_app/pic/Gallery_P.png
    - assets/
    - C:/Users/moski/Downloads/app/flutter_app/pic/Tri_ai.png
    - pic/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Medium.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700
    - family: SFpro
      fonts:
        - asset: fonts/SFPRODISPLAYREGULAR.otf
        - asset: fonts/SFPRODISPLAYMEDIUM.otf
          weight: 600
        - asset: fonts/SFPRODISPLAYBOLD.otf
          weight: 700

        # - asset: fonts/Schyler-Italic.ttf
        # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
